## Image Processing

In [1]:
import numpy as np
import cv2

In [47]:
img = cv2.imread('../imgs/butterfly.jpg')
img.shape # this shows number of rows, columns and channels

(338, 338, 3)

In [48]:
#returns total number of pixels in image
img.size

342732

In [6]:
px = img[100,100]
px # returns BGR value at that specific pixel location

array([153, 194, 203], dtype=uint8)

In [7]:
# accessing only blue pixel at specific location
blue_pix = img[100,100,0]
blue_pix

b,g,r = cv2.split(px)

153

In [9]:
# a better way of accesssing blue value
img.item(100,100,0)

153

### Modifying pixel values

In [10]:
# modifying pixels by assignment
img[100,100] = [255,255,255]
img[100,100]

array([255, 255, 255], dtype=uint8)

In [11]:
# a better way to modifying blue value 
img.itemset((10,10,0),100) 
img.item(10,10,0) 

100

### Region of Image (ROI)

In [49]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
patch = img[180:310, 180:310] 
img[0:130, 0:130] = patch

In [51]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
type(patch)

numpy.ndarray

In [57]:
#filling patch with white
patch.fill(255)

In [58]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Arithmetic Operations on images

#### Image Addition

The images to be added must be of the same size

In [64]:
img1 = cv2.imread('../imgs/butterfly.jpg')
img2 = cv2.imread('../imgs/sky.jpeg')

img1 = img1[:300,:300]
img2 = img2[:300,:300]

#result = cv2.add(img1,img2)
result = cv2.addWeighted(img1,0.7,img2,0.3,0)


cv2.imshow('Added Images',result)
cv2.imshow('Sky',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
img1.shape

(300, 300, 3)

In [25]:
img2.shape

(300, 300, 3)

In [60]:
img1

array([[[151, 187, 211],
        [151, 187, 211],
        [151, 187, 211],
        ..., 
        [151, 187, 211],
        [151, 187, 211],
        [151, 187, 211]],

       [[151, 187, 211],
        [151, 187, 211],
        [151, 187, 211],
        ..., 
        [151, 187, 211],
        [151, 187, 211],
        [151, 187, 211]],

       [[151, 187, 211],
        [151, 187, 211],
        [151, 187, 211],
        ..., 
        [151, 187, 211],
        [151, 187, 211],
        [151, 187, 211]],

       ..., 
       [[151, 187, 211],
        [150, 186, 210],
        [150, 186, 210],
        ..., 
        [150, 187, 207],
        [149, 189, 208],
        [149, 189, 208]],

       [[150, 186, 210],
        [150, 186, 210],
        [150, 186, 210],
        ..., 
        [152, 189, 209],
        [150, 190, 209],
        [150, 190, 209]],

       [[151, 187, 211],
        [151, 187, 211],
        [150, 186, 210],
        ..., 
        [152, 189, 209],
        [150, 190, 209],
        [150, 190,

In [61]:
img2

array([[[235, 231, 203],
        [243, 229, 200],
        [230, 197, 164],
        ..., 
        [201,  94,  50],
        [199,  94,  51],
        [199,  94,  51]],

       [[251, 240, 213],
        [253, 232, 204],
        [237, 199, 167],
        ..., 
        [201,  94,  50],
        [199,  94,  51],
        [199,  94,  51]],

       [[255, 236, 211],
        [251, 221, 194],
        [233, 186, 155],
        ..., 
        [201,  94,  50],
        [199,  94,  51],
        [199,  94,  51]],

       ..., 
       [[247, 228, 220],
        [248, 230, 219],
        [249, 230, 222],
        ..., 
        [245, 234, 226],
        [244, 235, 226],
        [243, 234, 225]],

       [[243, 223, 212],
        [243, 224, 211],
        [245, 225, 214],
        ..., 
        [247, 236, 228],
        [245, 235, 228],
        [244, 234, 227]],

       [[243, 219, 207],
        [243, 219, 207],
        [244, 220, 208],
        ..., 
        [246, 235, 227],
        [246, 234, 228],
        [246, 234,

### Thresholding

Explanation of thresholding

In [68]:
bookpage = cv2.imread('../imgs/bookpage.jpg',0)
bookpage

array([[16, 15, 15, ..., 13, 14, 15],
       [14, 14, 15, ..., 14, 15, 15],
       [13, 14, 15, ..., 14, 14, 14],
       ..., 
       [11, 10, 10, ..., 26, 28, 30],
       [12, 11, 11, ..., 28, 29, 29],
       [12, 11, 11, ..., 28, 29, 29]], dtype=uint8)

In [70]:
# simple binary thresholding
bookpage = cv2.imread('../imgs/bookpage.jpg',0)
ret, thresh_bin = cv2.threshold(bookpage, 12, 255, cv2.THRESH_BINARY)

cv2.imshow('Original', bookpage)
cv2.imshow('Binary Threshold', thresh_bin)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
# adaptive thresholding - this takes in different patches of the image and applies relative binary thresholding
# to different parts of the image.
#Takes in img,highest value,adptive threshold value,
#kind of threshold used,blocksize of pixel from which mean is calculated,
#constant subtracted from adaptive threshold

adapt_thresh = cv2.adaptiveThreshold(bookpage, 255, cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,85,3)

cv2.imshow('Original', bookpage)
cv2.imshow('Binary Threshold', thresh_bin)
cv2.imshow('Adaptive Threshold', adapt_thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Image transformations

### Resizing images

In [72]:
img3 = cv2.imread('../imgs/sky.jpeg')
inc = cv2.resize(img3,None,fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
dec = cv2.resize(img3,None,fx=0.5, fy=0.5, interpolation = cv2.INTER_CUBIC)

cv2.imshow('Original', img3)
cv2.imshow('Resize X 2', inc)
cv2.imshow('Resize X 0.5', dec)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Translation

In [74]:
img = cv2.imread('../imgs/sky.jpeg',0)
rows,cols = img.shape

M = np.float32([[1,0,200],[0,1,150]])
dst = cv2.warpAffine(img,M,(cols,rows))
cv2.imshow('img',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Rotation

In [77]:
img = cv2.imread('../imgs/sky.jpeg',0)
rows,cols = img.shape
# cols-1 and rows-1 are the coordinate limits/points about which to rotate, then angle, scale
M = cv2.getRotationMatrix2D(((cols-1)/2.0,(rows-1)/2.0),-100,1)
dst = cv2.warpAffine(img,M,(cols,rows))

cv2.imshow('img',dst)
cv2.waitKey(0) 
cv2.destroyAllWindows()

### Finding Edges

In [85]:
img = cv2.imread('../imgs/hillary_clinton.jpg',0)
edges = cv2.Canny(img,100,200)

cv2.imshow('img',img)
cv2.imshow('edges',edges)
cv2.waitKey(0)
cv2.destroyAllWindows()