# Review of Matrices

# What is Numpy?

NumPy is a fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object for our purpose of handling multi-dimensional arrays in Machine Learning.

# Why Numpy over Python Lists

* It consumes less memory.
* It is fast as compared to the python List.
* It is more convenient to use.

**Note: Python Lists can contain multiple data types but Numpy Arrays store values of the same data type**

## Overview of Python Lists

In [1]:
mylist = [2, 'boy', True, 3.4]
mylist

[2, 'boy', True, 3.4]

## Creating Numpy Arrays from Python Lists

In [1]:
# we first import numpy
import numpy as np

In [2]:
# integer arrays
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
# explicitly setting datatype
np.array([1,2,3,4,5], dtype='float32')

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

In [3]:
x = [5,6,7,8,9]
np.array(x)

array([5, 6, 7, 8, 9])

# Numpy Array Attributes & Datatypes

In [31]:
# let's look at a 1D array
x = np.array([1,2,3,4,5])

In [32]:
# array dimension
x.ndim

1

In [33]:
# array shape
x.shape

(5,)

In [34]:
# array size
x.size

5

In [38]:
# let's look at a 2D array
y = np.array([[1,2,3],
              [4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# array dimension
y.ndim

2

In [41]:
# array shape
y.shape

(2, 3)

In [42]:
# array size
y.size

6

In [49]:
# let's look at a 3D array
z = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              
             [[1,2,3],
               [4,5,6],
               [7,8,9]]])
z

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [50]:
# array dimension
z.ndim

3

In [51]:
# array shape
z.shape

(2, 3, 3)

In [53]:
# array size
z.size

18

In [57]:
#checking the datatype
z.dtype

dtype('int64')

# Creating Arrays from Scratch

In [5]:
# array filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.zeros((2,3,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [6]:
# array filled with ones
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
# array filled with a particular number
np.full((3,4),3.14)

array([[ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14]])

In [7]:
# arange() fuction similar to range() in Python
# arange(start,stop,step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# linspace(start,stop,num_of_values)
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [24]:
# random values uniformly distributed between 0 and 1
np.random.random((3,3))

array([[ 0.7841255 ,  0.44892447,  0.59109926],
       [ 0.83606991,  0.63333939,  0.84621356],
       [ 0.50259432,  0.13136339,  0.65510983]])

In [6]:
# random integers between the values of 1-10
np.random.randint(1, 10,(3,3))

array([[7, 8, 8],
       [4, 4, 6],
       [1, 5, 6]])

# Array Indexing

In [7]:
# this is similar to indexing lists
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a[3]

3

In [16]:
# 2D indexing
b = np.random.randint(0, 10,(3,3))
b

array([[4, 0, 9],
       [0, 5, 4],
       [0, 0, 6]])

In [17]:
print(b[0])
print(b[-1])

[4 0 9]
[0 0 6]


In [18]:
print(b[0,2])
print(b[1,2])

9
4


# Value Assignments

In [19]:
print(b)
b[2,1] = 99
b

[[4 0 9]
 [0 5 4]
 [0 0 6]]


array([[ 4,  0,  9],
       [ 0,  5,  4],
       [ 0, 99,  6]])

In [90]:
b[0,0] = 64
b

array([[64,  9,  4],
       [ 5,  0,  3],
       [ 6, 99,  3]])

# Array Slicing

In [74]:
# 1D Array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a[0:3]

array([0, 1, 2])

In [76]:
a[2:7]

array([2, 3, 4, 5, 6])

In [81]:
# a[start:stop:step]
a[2:7:2]

array([2, 4, 6])

In [77]:
a[:4]

array([0, 1, 2, 3])

In [78]:
a[5:]

array([5, 6, 7, 8, 9])

In [79]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 2D Array
b = np.random.randint(0, 10,(3,3))
b

array([[4, 0, 2],
       [8, 6, 0],
       [5, 8, 4]])

In [27]:
b[0:2, 0:2]

array([[4, 0],
       [8, 6]])

In [22]:
b[0,:]

array([6, 6, 6])

In [23]:
b[:,0]

array([6, 7, 8])

# Reshaping of Arrays

In [29]:
# the size of the initial array must match the size of the reshaped array.
c = np.arange(1,10) # 1D
d = c.reshape(3,3) # 2D
print(c)
print()
print(d)


[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Concatination of Arrays

In [96]:
# 1D concatination

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [33]:
# 2D concatination
e = np.array([[1, 2, 3],
              [4, 5, 6]])

d = np.concatenate([e,e])
d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [36]:
print(e.shape)
print(d.shape)

(2, 3)
(4, 3)


# Array Arithmetic

In [17]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("x ** 2 =", x**2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]


In [38]:
# This results in an error, you cannot do arithmetic operations on lists like in Numpy arrays 
mylist = [1,2,3,4]
mylist + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
# This results in an error, you cannot do arithmetic operations on lists like in Numpy arrays 
mylist2 = [1,2,3,4]
mylist2 + 1

In [108]:
# we are creating our 2D array to do computation with them.

m = np.array([1,2,3,4,4,3,2,1]).reshape(4,2)
m

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [39]:
n = np.array([5,6,7,8,8,7,6,5]).reshape(4,2)
n

array([[5, 6],
       [7, 8],
       [8, 7],
       [6, 5]])

In [111]:
m + n

array([[ 6,  8],
       [10, 12],
       [12, 10],
       [ 8,  6]])

In [112]:
n - m

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [113]:
n * m

array([[ 5, 12],
       [21, 32],
       [32, 21],
       [12,  5]])

In [114]:
m / n

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ],
       [ 0.5       ,  0.42857143],
       [ 0.33333333,  0.2       ]])

In [115]:
m % n

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [29]:
# dot product
a = np.random.randint(0,10,(3,3))
a

array([[2, 4, 5],
       [2, 7, 6],
       [5, 1, 8]])

In [30]:
b = np.random.randint(0,10,(3,1))
b

array([[6],
       [4],
       [9]])

In [31]:
a.dot(b)

array([[ 73],
       [ 94],
       [106]])