# Drawing shapes

In [4]:
import numpy as np
import cv2

In [5]:
# Create a black image 
img = np.zeros((512,512,3), np.uint8)
print(img)
cv2.imshow('Black Screen',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


### Drawing a line

In [6]:
# Draw a diagonal blue line which starts from point (0,0) to point (511,511) with thickness of 5 px 
img = cv2.line(img,(0,0),(511,511),(255,0,0),5)

In [7]:
#showing the image with the blue line
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a rectangle

In [14]:
# retangle takes the top-left corner and bottom-right corner points 
img = cv2.rectangle(img,(384,0),(510,128),(0,255,0),10)

In [15]:
#showing the image with the blue line and green rectangle
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing a circle

In [12]:
# takes in the point for the circumference, radius, color and line width
img = cv2.circle(img,(345,63), 63, (0,0,255), -1)

In [13]:
#showing the image with the red circle
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Adding Texts

In [17]:
#check out other types of cv2 fonts
font = cv2.FONT_HERSHEY_SIMPLEX

#putText() takes in the image, text, starting position coordinates, font type, font size,color, line thickness and line type
cv2.putText(img, 'Hello World!', (10,500), font, 2, (255,255,255), 2, cv2.LINE_AA)

#showing the image with the blue line
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Mouse as a Paint Brush Demo

In [18]:
img2 = np.ones((512,512,3), np.uint8)*255
img2

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [19]:
cv2.namedWindow('Paint Program',cv2.WINDOW_NORMAL)
cv2.imshow('Paint Program',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [132]:
#to view all available mouse events
events = [i for i in dir(cv2) if 'EVENT' in i] 
events

['EVENT_FLAG_ALTKEY',
 'EVENT_FLAG_CTRLKEY',
 'EVENT_FLAG_LBUTTON',
 'EVENT_FLAG_MBUTTON',
 'EVENT_FLAG_RBUTTON',
 'EVENT_FLAG_SHIFTKEY',
 'EVENT_LBUTTONDBLCLK',
 'EVENT_LBUTTONDOWN',
 'EVENT_LBUTTONUP',
 'EVENT_MBUTTONDBLCLK',
 'EVENT_MBUTTONDOWN',
 'EVENT_MBUTTONUP',
 'EVENT_MOUSEHWHEEL',
 'EVENT_MOUSEMOVE',
 'EVENT_MOUSEWHEEL',
 'EVENT_RBUTTONDBLCLK',
 'EVENT_RBUTTONDOWN',
 'EVENT_RBUTTONUP']

### Drawing dots on mouse clicks

In [21]:
#drawing dots on mouse clicks

def draw_circle(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img2,(x,y),3,(255,0,0),-1)

img2 = np.ones((512,512,3), np.uint8)*255
cv2.namedWindow('Paint Program', cv2.WINDOW_NORMAL)
      
cv2.setMouseCallback('Paint Program', draw_circle)

while(1):
    cv2.imshow('Paint Program',img2)
    if cv2.waitKey(0) == 27:
        break
cv2.destroyAllWindows()

### Drawing on mouse movement

In [26]:
#drawing on mouse movement

canvas = np.ones((512,512,3), np.uint8)*255
color = (0,255,0)
radius = 3
pressed = False


def draw(event, x, y, flags, params):
    global canvas, pressed, radius
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(canvas,(x,y),radius,color,-1)
        pressed = True
        #print('pressed')
    elif event == cv2.EVENT_MOUSEMOVE and pressed == True:
        cv2.circle(canvas,(x,y),radius,color,-1)
        #print('drawing...')
    elif event == cv2.EVENT_LBUTTONUP:
        pressed = False
        #print('stopped drawing')
        
#window initialization and callback function
cv2.namedWindow('Paint Program', cv2.WINDOW_NORMAL)
cv2.setMouseCallback('Paint Program', draw)

while True:
    cv2.imshow('Paint Program',canvas)
    
    k = cv2.waitKey(1)
    if k == 27:
        break
    elif k == ord('r'):
        color = (0,0,255)
        print('Red pen color')
    elif k == ord('g'):
        color = (0,255,0)
        print('Green pen color')
    elif k == ord('b'):
        color = (255,0,0)
        print('Blue pen color')
    elif k == ord('s'):
        cv2.imwrite('myDrawing2.png',canvas)
        print('Drawing saved')
        
cv2.destroyAllWindows()

Red pen color
Green pen color
Red pen color
Blue pen color
Drawing saved
Drawing saved
